name: rezume_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  responsive_framework: ^1.1.1
  # carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
